#NAME: Vincent Chi
#EMAIL: vincentchi9702@gmail.com
#ID: 304576879

default: dist

dist:
	tar -cvzf lab4a-304576879.tar.gz my_beaglebone.jpg connected.png copy.png git.png build_run.png README Makefile
