#NAME: Vincent Chi EMAIL: vincentchi9702@gmail.com ID: 304576879
default:
	chmod +x lab3b.sh
	-ln lab3b.sh lab3b
clean:
	rm -f lab3b lab3b-304576879.tar.gz
dist:
	tar -czvf lab3b-304576879.tar.gz lab3b.sh lab3b.py Makefile README
