#vincent chi 304576879 vincentchi9702@gmail.com
default:lab3a.cpp
	g++ -Wall  -Wextra lab3a.cpp -o lab3a

clean:
	rm -rf lab3a-304576879.tar.gz lab3a
dist:
	tar -czvf lab3a-304576879.tar.gz lab3a.cpp ext2_fs.h Makefile README
